data:
  path: /morad_dir/Datasets/EMAD/
  annotation_file: morad.csv
  frames: 16
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
model:
  freeze: True
  pretrained_weights: /morad_dir/modelsWeights/mae_pretrain_vit_base.pth
  proj_dropout: 0.1
  transformer_head:
    frames: 16
    width: 192
    layers: 12
    heads: 3
    attn_dropout: 0.1
    mlp_dropout: 0.1
    out_features: 4
    dropout: 0.1
    out_pool: avg
train:
  epochs: 100
  lr: 3.e-5
  batch_size: 128
  num_workers: 2
  pin_memory: False
  checkpoint_interval: 101
  log_dir: /morad_dir/weights/MORAD/TEST/mae
  seed: 42