data:
  path: /morad_dir/Datasets/EMAD/
  annotation_file: morad.csv
  frames: 16
model:
  freeze: True
  pretrained_weights: /morad_dir/modelsWeights/clip_rn101.pt
  proj_dropout: 0.3
  transformer_head:
    frames: 16
    width: 192
    layers: 12
    heads: 3
    attn_dropout: 0.3
    mlp_dropout: 0.3
    out_features: 4
    dropout: 0.3
    out_pool: avg
train:
  epochs: 100
  lr: 1.e-4
  batch_size: 128
  num_workers: 2
  checkpoint_interval: 101
  log_dir: /morad_dir/weights/MORAD/TEST/resnet
  seed: 42