data:
  path: /morad_dir/Datasets/EMAD/
  annotation_file: morad.csv
  frames: 16
  processor: facebook/timesformer-base-finetuned-k400
model:
  out_features: 4
  name: facebook/timesformer-base-finetuned-k400
train:
  epochs: 100
  lr: 1.e-6
  batch_size: 16
  num_workers: 2
  checkpoint_interval: 101
  log_dir: /morad_dir/weights/MORAD/TEST/timesformer
  seed: 42