data:
  path: /morad_dir/Datasets/EMAD/
  annotation_file: morad.csv
  frames: 32
  processor: 'google/vivit-b-16x2-kinetics400'
model:
  out_features: 4
  name: 'google/vivit-b-16x2-kinetics400'
train:
  epochs: 100
  lr: 1.e-6
  batch_size: 4
  num_workers: 2
  checkpoint_interval: 101
  log_dir: /morad_dir/weights/MORAD/TEST/vivit
  seed: 42