data:
  annotation_file: morad.csv
  path: /morad_dir/Datasets/EMAD/
  tokenizer: UBC-NLP/MARBERTv2
model:
  model_name: UBC-NLP/MARBERTv2
  dropout: 0.1
  out_features: 4
train:
  epochs: 100
  lr: 1.e-5
  batch_size: 128
  num_workers: 2
  checkpoint_interval: 101
  log_dir: /morad_dir/weights/MORAD/TEST/bert
  seed: 42