data:
  annotation_file: morad.csv
  path: /morad_dir/Datasets/EMAD/
  tokenizer: 3ebdola/Dialectal-Arabic-XLM-R-Base
model:
  model_name: 3ebdola/Dialectal-Arabic-XLM-R-Base
  dropout: 0.3
  out_features: 4
train:
  epochs: 100
  lr: 5.e-5
  batch_size: 128
  num_workers: 2
  checkpoint_interval: 101
  log_dir: /morad_dir/weights/MORAD/TEST/roberta
  seed: 42