data:
  path: /morad_dir/Datasets/EMAD/
  annotation_file: morad.csv
model:
  freeze: false
  pretrained_weights: /morad_dir/modelsWeights/hubert-large-ls960-ft-pre.pt
  proj_dropout: 0.2
  transformer_head:
    frames: 251
    width: 192
    layers: 12
    heads: 3
    attn_dropout: 0.2
    mlp_dropout: 0.2
    out_features: 4
    dropout: 0.2
    out_pool: avg
train:
  epochs: 100
  lr: 5.e-5
  batch_size: 32
  num_workers: 2
  checkpoint_interval: 101
  log_dir: /morad_dir/weights/MORAD/TEST/hubert
  seed: 42
notes:
  - Not freezing
  - Trying with high learning rates