data:
  path: /morad_dir/Datasets/EMAD/
  annotation_file: morad.csv
  spectorgram_config:
    img_size: 232
    transforms: false
model:
  resnet: resnet101
  out_features: 4
train:
  epochs: 100
  lr: 1.e-5
  batch_size: 128
  num_workers: 2
  checkpoint_interval: 101
  log_dir: /morad_dir/weights/MORAD/TEST/mscnn
  seed: 42
notes:
  - Back to not supporting dropout