data:
  path: /morad_dir/Datasets/EMAD/
  annotation_file: morad.csv
model:
  freeze: true
  pretrained_weights: /morad_dir/modelsWeights/whisper_large.pt
  proj_dropout: 0.1
  transformer_head:
    frames: 1500
    width: 192
    layers: 12
    heads: 3
    attn_dropout: 0.
    mlp_dropout: 0.
    out_features: 4
    dropout: 0.
    out_pool: avg
train:
  epochs: 100
  lr: 1.e-4
  batch_size: 128
  num_workers: 2
  checkpoint_interval: 101
  log_dir: /morad_dir/weights/MORAD/TEST/whisper
  seed: 42